Repository AY2122S2-CS2103T-W14-3/tp, pull requests merged in 2022-03, with the labels that each got.

#10 Add Steven's skeletal PPP
  docs/team/graphcalibur.md
Labels: awaiting review

#18 Add Edward Skeletal PPP
  .gitignore
  docs/AboutUs.md
  docs/images/theprevailingone.jpeg
  docs/team/theprevailingone.md
Labels: awaiting review

#37 Fix and Clean About Us Page
  docs/AboutUs.md
  docs/images/johndoe.png
  docs/images/theprevailingone.png
Labels: documentation

#43 Add delete_event command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: enhancement, awaiting review

#81 Fix sample data to make sure that the date format is correct.
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: awaiting review, priority: high

#83 Update user guide
  docs/UserGuide.md
  docs/images/UserGuide/Ui-1.png
  docs/images/UserGuide/Ui-2.png
  docs/images/UserGuide/Ui-3.png
  docs/images/UserGuide/Ui-4.png
Labels: documentation, awaiting review

#86 Improve find functionalities
  src/main/java/seedu/address/logic/commands/FindCompanyCommand.java
  src/main/java/seedu/address/logic/commands/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/FindEventCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
  src/main/java/seedu/address/model/entry/CompanyNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/entry/Date.java
  src/main/java/seedu/address/model/entry/Event.java
  src/main/java/seedu/address/model/entry/Location.java
  src/main/java/seedu/address/model/entry/Time.java
  src/main/java/seedu/address/model/entry/predicate/CompanyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/entry/predicate/CompanyNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/entry/predicate/DateContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/entry/predicate/EventContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/entry/predicate/LocationContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/entry/predicate/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/entry/predicate/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/entry/predicate/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/entry/predicate/TimeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindPersonCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: enhancement, awaiting review

#87 User guide update
  docs/UserGuide.md
Labels: enhancement, awaiting review
